# Generated by Django 2.1.2 on 2019-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.CharField(max_length=50)),
                ('food_image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('usermobile', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=50)),
                ('userpassword', models.CharField(max_length=50)),
                ('user_image', models.CharField(max_length=50)),
            ],
        ),
    ]
